name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-
      - run: go get -d
      - run: go test ./... -tags=chaos -race -v

  vet:
    name: Static
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - uses: actions/checkout@v2
      - run: go vet
      - name: go fmt
        run: (! gofmt -s -d | grep '^')

  security:
    name: Security
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
