name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-
      - run: go test ./... -tags=chaos -v
